apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-ingress
  namespace: home
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: rag.k6n.net
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: rag-service
                port:
                  number: 4001
          - path: /assets
            pathType: Prefix
            backend:
              service:
                name: rag-service
                port:
                  number: 4001
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: rag-service
                port:
                  number: 4001
          - path: /api/auth/device
            pathType: Exact
            backend:
              service:
                name: rag-frontend
                port:
                  number: 3000
          - path: /api/auth/tokens
            pathType: Prefix
            backend:
              service:
                name: rag-service
                port:
                  number: 4001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-frontend
                port:
                  number: 3000
  tls:
    - hosts:
        - rag.k6n.net
      secretName: rag-k6n-net-tls
